version: "3.7"
services:
  app-server:
    build: /workspace/dockerapp
    image: garciaong/dockerapp:1.0.0
    ports:
      - "80:8080"
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "1"
          memory: 256M
      restart_policy:
        condition: on-failure
    networks: 
      - springboot-network
    volumes:
      - "/mnt/sda1/host/map/docker:/log"
  data-server:
    build: /workspace/dockerdata
    image: garciaong/dockerdata:1.0.0
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "1"
          memory: 256M
      restart_policy:
        condition: on-failure
    ports:
      - "81:8080"
    networks: 
      - springboot-network
    volumes:
      - "/mnt/sda1/host/map/docker:/log"
networks:
  springboot-network: {}